### ISSUE TITLE
Move from detection to implementation (WebPJS)

### ISSUE THREAD

**Issue by Dade88** [yireo/plg_system_webp#2]
I think the plugin could improve a lot by deleting all the detection methods - or just make them optional - and use [WebPJS](http://webpjs.appspot.com/) instead.

As your plugin already help to convert images to WebP, and we can make all browsers compatible with WebPJS, it would have much more benefits (and you get rid of creating additional cookies).

**Comment by yireo** [comment]
Why do you think this, apart from that this third party JavaScript already exists? I checked and I can see that the code works for some part. However, it does not allow for checking whether a WebP image exists for a certain source image. Plus it does not support PHP GD, but only assumes that all images are there, leading to a lot of scripting on top of this library to make things work anyway. I appreciate the gesture, but I think this would require a completely different approach and a completely different solution.

**Comment by Dade88** [comment]
Maybe I didn't explain myself clearly. WebPJS is a single script, so instead of trying to detect browsers compatibility the actual way, you could either simply place the script or use IFs on the php side like
`if(isset($_SERVER['HTTP_USER_AGENT'])){
    $agent = $_SERVER['HTTP_USER_AGENT'];
}
if(strlen(strstr($agent,"Firefox")) > 0 ){      
    $browser = 'firefox';
}
if($browser=='firefox'){
    echo '<script type="text/javascript" src="js/webpjs-0.0.2.min.js"></script>';
}`

As for the WebP Images, I understand your plugin actually converts them so they should be there anyway.

Thx for your time :)
